database: 'mongodb://localhost'
server-data:
  bungee-name: 'lobby-1'
  display-name: '&aLobby-1'
  description: '&7Lobby server'
  type: 'LOBBY'
spawn:
  x: 0.0
  y: 100.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
  world: 'world'