# Database connect URI, use 'mongodb://localhost' for default connection
database: 'mongodb://localhost'

# Autosaves Factions, Players and Claims at a set interval
autosave:
  enabled: true
  interval: 900

# Factions configuration, here's what most of it does:
# Member-cap: Max members faction can have
# Reinvites: Re-invites new factions receive upon creation and Palace being captured
# Home-height-cap: Max Y height home can be set at
# Max-DTR: Max DTR can be for a faction
# Tick-Interval: Time (in seconds) the plugin attempts to perform regeneration logic for a faction,
# this number is subtracted from by (tick-subtract-per-player * onlinePlayerSize)
# Per-player-DTR-value: Value each player holds in the max DTR
factions:
  member-cap: 30
  reinvites: 5
  home-height-cap: 100
  max-dtr: 7.0
  tick-interval: 60
  tick-subtract-per-player: 1
  per-player-dtr-value: 0.4
  naming:
    min: 3
    max: 16
    blocked-names:
      - 'admin'
      - 'mod'
      - 'administrator'
      - 'moderator'
      - 'owner'
      - 'palace'
      - 'citadel'

# Claiming configuration, here's what it all means:
# Min-size: Minimum size each side of a claim needs to be. E.g (10 = 10x10)
# Max-claims: Max amount of claims a faction is allowed to have. Any more than 3 and factions could
# technically box others in or even make claims around whole events
# Block-value: Value that each block holds when determining the cost of a claim (area * block-value)
# Refunded-Percent: The amount refunded to a faction after unclaiming land (0.75 = 75%)
# Buffers determine the distance (in blocks) you need to be from another factions claim when creating
# a new claim.
claims:
  min-size: 10
  max-claims: 3
  block-value: 10.0
  refunded-percent: 0.75
  buffers:
    player: 16.0
    server: 250.0

# Timer configuration
timers:
  player:
    combat-tag:
      attacker: 60
      attacked: 5
    protection: 1800
    enderpearl: 16
    totem: 7200
    gapple: 3600
    crapple: 10
    home: 10
    stuck: 180
  faction:
    freeze: 3600
    rally: 10

# Lives configuration
# If disabled, players will not be able to revive themselves and will be forced to wait out deathbans
# If a rank is not listed in the Ranks area, they will not receive lives upon logging in to a new map
lives:
  enabled: true
  ranks:
    Basic: 2
    Premium: 6
    Ultra: 10
    Partner: 10

# Crowbar configuration
crowbars:
  enabled: true
  allowed-spawner-types:
    - 'ZOMBIE'
    - 'SKELETON'
    - 'SPIDER'
    - 'CAVE_SPIDER'

# Deathban configuration
# If disabled, players will respawn normally
# The durations are in seconds
deathbans:
  enabled: true
  durations:
    SOTW:
      min: 300
      max: 3600
    NORMAL:
      min: 300
      max: 86400
    EOTW:
      min: 86400
      max: 86400

# Economy configuration
economy:
  starting-balance: 100.0

# Mining configuration
# Findables can be defined here, allowing for custom ore spawning of any type
mining:
  enabled: true
  findables:
    GLOWSTONE:
      rate: 0.01
      found-in: 'NETHERRACK'
      height:
        min: 1
        max: 256
      world: 'NETHER'
      vein-size:
        min: 5
        max: 15
      broadcast: false
      message: true
      color: '6'
    DIAMOND_ORE:
      rate: 0.0125
      found-in: 'STONE'
      height:
        min: 1
        max: 16
      world: 'NORMAL'
      vein-size:
        min: 2
        max: 8
      broadcast: true
      message: false
      color: 'b'
    EMERALD_ORE:
      rate: 0.01
      found-in: 'STONE'
      height:
        min: 1
        max: 16
      world: 'NORMAL'
      vein-size:
        min: 2
        max: 8
      broadcast: true
      message: false
      color: 'a'

# Stats configuration
stats:
  enabled: true
  starting-elo: 0
  elo-modifiers:
    kill: 25
    death: 25
    minor-capture: 75
    major-capture: 200

# Combat logger configuration
loggers:
  enabled: true
  logger-duration: 30
  enemy-radius: 16