database: 'mongodb://localhost'

server-sync:
  id: 1
  bungee-name: 'arena'
  display-name: '&9Arena'
  description: '&7Arena Description'
  type: 'ARENA'
  premium-allocated-slots: 200

limits:
  team-size: 30

timers:
  invite-expire: 30
  challenge-expire: 30
  report-expire: 180

spawn:
  x: 0.0
  y: 100.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0
  world: 'world'